### ISSUE TITLE
Plug In:  No Page Comment

### ISSUE THREAD

**Issue by FAuser2015** [sethta/no-page-comment#4]
I was getting a ton of spam and my current host wanted me to fix the spam/bot traffic.  I tried various plug-ins and I couldn't get the issue fixed.  At that point, I decided to remove the 'Comments' section from my blog all together..figured that would eliminate spam comments/spam traffic.  However, after I installed this plug in all of my content has disappeared from my web page....is there a way to revert back or turn it back on?  it appears the text portion of the theme I use..which is "Cooking Press" must be set up as comment boxes?! Maybe.  Basically I need urgent help because I have 0 content on my page right now but the content is in my admin posts folder, just not on my page published.  I also didn't backup my site before activating the plug in.

**Comment by sethta** [comment]
I don't think that the issue would have been caused from this plugin, as it only sets the default setting for new posts/pages/custom post types. It doesn't touch the front-end of a site at all.

The only other setting that the plugin controls is disabling all comments, but it will still leave previous comments on. Also, when you click the button to disable all comments, it alerts you that the process is irreversible, and has you confirm that you really want to do it. If you need to turn on comments that were previously on before clicking the button, you will have to do it manually.

I personally believe that this could have been caused from another plugin, or if you made any modifications to your theme. My recommendation is to first try disabling all plugins, and see if that fixes something. If it does then you know that it is an issue with one of the plugins. Then turn them all on one by one, and figure out which plugin caused it. If it ends up being No Page Comment, please let me know the error message that is associated (you will need to set WP_DEBUG to true in your wp-config.php file).

If it is not a plugin, then I'd recommend changing your theme to the default TwentyFifteen theme. If you content is there, then you know the issue is coming from your theme.

Finally, if that doesn't work, then it's an issue either with a corruption in your core WordPress installation, an issue with your database, a potential hacking, or an issue with your server.

**Comment by FAuser2015** [comment]
I disabled all of my plugins and my content still doesn't show up.  I haven't made any modifications to my theme and I'm also not very coding savvy.

what do you mean by WP_DEBUG to true in my wp-config.php file?  how do I do that and what will that do?
